# Site settings
title: Loyal Heart of the Sky Patrol
email: 2829777585@qq.com
description: >- 
  A personal blog about programming, finance, and life reflections.
baseurl: ""
url: "https://advanture917.github.io" 
twitter_username: adventure_917
github_username: advanture917

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO settings
lang: en
author: Your Name
social:
  name: Your Name
  links:
    - https://twitter.com/your_username
    - https://github.com/your_username