# Site settings
title: Loyal Heart of the Sky Patrol
email: 2829777585@qq.com
description: >- 
  A modern personal blog about programming, finance, and life reflections. 
  Featuring clean design, dark mode, and responsive layout.
baseurl: ""
url: "https://advanture917.github.io" 
twitter_username: adventure_917
github_username: advanture917

# Modern blog settings
show_excerpts: true
header_pages:
  - about.markdown
  - archive.html
  - tags.html

# Theme customization
theme_config:
  enable_dark_mode: true
  enable_search: true
  enable_tag_cloud: true
  show_reading_time: true
  show_post_nav: true
  enable_social_share: true

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination
paginate: 8
paginate_path: "/page:num/"

# Reading time calculation
reading_time: true

# Comments (optional)
comments:
  provider: "disqus"  # false (default), "disqus", "utterances"
  disqus:
    shortname: "your-disqus-shortname"

# Analytics (optional)
analytics:
  provider: "google-gtag"  # false (default), "google", "google-universal", "google-gtag"
  google:
    tracking_id: "G-XXXXXXXXXX"
    anonymize_ip: false

# SEO settings
lang: en
author: 
  name: advanture917
  bio: "A passionate developer sharing knowledge through modern blogging"
  avatar: "/assets/images/avatar.jpg"
  location: "Earth"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:2829777585@qq.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/advanture917"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/adventure_917"

social:
  name: advanture917
  links:
    - https://twitter.com/adventure_917
    - https://github.com/advanture917